
version: '3.4'

services:
  project:
    image: project
    build:
      context: .
      dockerfile: Project/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
